version: '3.4'

services:
  api:
    image: retriever
    networks:
      - default
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  db:
    image: "postgres" # use latest official postgres version
    networks:
      - default
    ports:
      - 5405:5432
    env_file:
      - database.env # configure postgres
    volumes:
      - db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  db-data: # named volumes can be managed easier using docker-compose
