version: '3.4'

services:
  api:
    container_name: json_parser
    image: retriever
    networks:
      - parser
    depends_on:
      - db
    environment:
      - DB_HOST=postgres_container
    env_file:
      - database.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  db:
    container_name: postgres_container
    image: postgres
    networks:
      - parser
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
        - postgres:/data/postgres


networks:
  parser:
    driver: bridge

volumes:
    postgres:
